# Generated by Django 3.0.3 on 2020-02-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='isPublic',
            field=models.BooleanField(default=False),
        ),
    ]
